### ISSUE TITLE
[Feature] Provide configuration via config files

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/reviews#115]
**Is your feature request related to a problem? Please describe.**
Users have requested the ability to set configuration using config files on their file system (instead of using env vars for secrets such as a GITHUB_TOKEN). These files could be encrypted at rest to ensure secrets are not readable outside of the application 

**Describe the solution you'd like**
support for config files on windows, linux, mac to allow a github token to be provided via a config file - instead of an env var. 

the order of preference should be env var (if set), otherwise, default to file system for configuration.

**Additional context**
I'm open to discussing how folks would like to implement this - feedback and suggestions welcome in the comments.

**Comment by waynew** [comment]
This is actually kind of possible already? Since you've already [using decouple](https://pypi.org/project/python-decouple/) it appeared to work for free the first time I tried it in editable mode(?)

Was just reviewing #128 though and it didn't appear to work the way I had used the .env file before.

At least in my testing I was able to work around it by throwing the env vars in a script (though, they're still env vars).

an approach that I've taken in other applications is to provide either an env var/command line arg to a `--config=/path/to/file` or something like that.

**Comment by apoclyps** [comment]
thanks for the feedback; the above approach sounds good to me 👍 

using either an env var or `--config=` command-line argument to supply the path to the `settings.ini` or `.env`: https://pypi.org/project/python-decouple/#where-the-settings-data-are-stored

**Comment by apoclyps** [comment]
I've added a `PATH_TO_CONFIG` env var to provide configuration outside of module/repository and adds PATH_TO_CONFIG to the `config` command:

![120181350-d5f20d80-c204-11eb-8c4c-1f2847f9215d](https://user-images.githubusercontent.com/1443700/120182318-24ec7280-c206-11eb-8684-2547f259c7b5.png)

adding `--config=` will require additional work to refactor how configuration is currently initialised and retrieved. for now `PATH_TO_CONFIG` provides enough functionality to provide the behaviour listed above.
